cube/urls.py
from django.contrib import admin
from django.urls import path, include
from django_registration.backends.one_step.views import RegistrationView

from accounts.views import ProfileView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', ProfileView.as_view()),

    path('source/', include('source.urls')),

    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django_registration.backends.one_step.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

]

source/urls.py
from django.urls import path

from source.views import SourceListView, SourceCreateView, SourceEditView, SourceDetailView, SourceDeleteView, \
    SourceActionView

urlpatterns = [
    path('', SourceListView.as_view(), name='source_list'),
    path('create/', SourceCreateView.as_view(), name='source_create'),
    path('action/', SourceActionView.as_view(), name='source_action'),
    path('edit/<int:source_id>/', SourceEditView.as_view(), name='source_edit'),
    path('detail/<int:source_id>/', SourceDetailView.as_view(), name='source_detail'),
    path('delete/<int:source_id>/', SourceDeleteView.as_view(), name='source_delete'),
]

source/models.py
from django.db import models

from accounts.models import User


class SourceManager(models.Manager):

    def active(self):
        return self.filter(archived=False)

    def archive(self):
        return self.filter(archived=True)


class Source(models.Model):
    IMPORT_TYPES_CHOICES = (
        ('yml_site', 'YML с сайта'),
        ('yml_file', 'YML файл')
    )

    name = models.CharField('Название источника', max_length=200)
    description = models.TextField('Описание', null=True, blank=True)
    user = models.ForeignKey(User, related_name='sources', on_delete=models.CASCADE)
    import_type = models.CharField('Тип импорта', choices=IMPORT_TYPES_CHOICES, default='yml_site', max_length=50)

    import_yml_url = models.URLField('Ссылка на yml файл', max_length=400, null=True, blank=True)
    import_yml_file = models.FileField('YML файл', upload_to='yml_files', null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    archived = models.BooleanField(default=False)

    objects = SourceManager()

    def __str__(self):
        return self.name

    def to_archive(self):
        self.archived = True
        self.save()

    def to_active(self):
        self.archived = False
        self.save()

source/forms.py
from django import forms

from source.models import Source


class SourceCreateForm(forms.ModelForm):

    def clean(self):
        cleaned_data = super().clean()
        if cleaned_data['import_type'] == 'yml_site' and not cleaned_data['import_yml_url']:
            self.add_error('import_yml_url', 'Нужно указать ссылку на yml файл')
        if cleaned_data['import_type'] == 'yml_file' and not cleaned_data['import_yml_file']:
            self.add_error('import_yml_file', 'Нужно загрузить файл yml')
        return cleaned_data

    class Meta:
        model = Source
        fields = ['name', 'description', 'import_type', 'import_yml_file', 'import_yml_url']


class SourceChangeForm(forms.ModelForm):

    class Meta:
        model = Source
        fields = ['name', 'description']

source/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View

from cube.base_views import CabinetListView, CabinetCreateView, CabinetUpdateView, CabinetDetailView, CabinetActionView
from source.forms import SourceCreateForm, SourceChangeForm
from source.models import Source


class SourceListView(CabinetListView):
    template_name = 'source_list.html'
    title = 'Источники товаров'
    page_head = title
    head_icon = 'cloud-upload'
    active_menu_items = 'sources:list'
    context_object_name = 'sources'
    queryset = Source.objects.active()
    paginate_by = 20

    def get_queryset(self):
        return self.queryset.filter(user=self.request.user)


class SourceCreateView(CabinetCreateView):
    template_name = 'source_create.html'
    title = 'Новый источник'
    page_head = title
    head_icon = 'plus'
    active_menu_items = 'sources:new'
    form_class = SourceCreateForm
    success_url = reverse_lazy('source_list')

    def form_valid(self, form):
        source = form.save(commit=False)
        source.user = self.request.user
        source.save()
        messages.add_message(self.request, messages.SUCCESS, 'Источник создан')
        return super().form_valid(form)


class SourceEditView(CabinetUpdateView):
    template_name = 'source_change.html'
    head_icon = 'pen'
    active_menu_items = 'sources:list'
    form_class = SourceChangeForm
    queryset = Source.objects.active()
    success_url = reverse_lazy('source_list')

    def get_queryset(self):
        return self.queryset.filter(user=self.request.user)

    def get_title(self):
        source = self.get_object()
        return f'Редактирование источника: "{source.name}"'

    def get_head(self):
        return self.get_title()

    def form_valid(self, form):
        form.save()
        messages.add_message(self.request, messages.SUCCESS, 'Источник изменен')
        return super().form_valid(form)


class SourceDetailView(CabinetDetailView):
    template_name = 'source_detail.html'
    head_icon = 'note2'
    active_menu_items = 'sources:list'
    queryset = Source.objects.active()

    def get_queryset(self):
        return self.queryset.filter(user=self.request.user)

    def get_title(self):
        source = self.get_object()
        return f'Редактирование источника: "{source.name}"'

    def get_head(self):
        return self.get_title()


class SourceDeleteView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        source = get_object_or_404(Source, pk=kwargs['source_id'], user=request.user)
        source.to_archive()
        messages.success(request, 'Источник "{}" был перемещен в архив'.format(source.name))
        return HttpResponseRedirect(reverse('source_list'))


class SourceActionView(CabinetActionView):

    def view_action_delete(self, request, id_list):
        Source.objects.active().filter(user=request.user, pk__in=id_list).update(archived=True)
        messages.success(request, "Источники были перемещены в архив")
        return HttpResponseRedirect(reverse('source_list'))

source/templates/source_change.html
{% extends 'cabinet_base.html' %}
{% load render_bundle from webpack_loader %}
{% load bootstrap4 %}
{% block main_area %}
    <div class="row">
        <div class="col-6 mx-auto">
            <div class="card card-body mb-2">
                <form action="" method="post" class="position-relative">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="divider row"></div>
                    <div class="d-flex align-items-center">
                        <div class="ml-auto">
                            <button class="btn btn-primary btn-lg">Сохранить</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

source/templates/source_create.html
{% extends 'cabinet_base.html' %}
{% load render_bundle from webpack_loader %}
{% load bootstrap4 %}
{% block main_area %}
    <div class="row">
        <div class="col-6 mx-auto">
            <div class="card card-body mb-2">
                <form action="" method="post" class="position-relative" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% bootstrap_form form %}
                    <div class="divider row"></div>
                    <div class="d-flex align-items-center">
                        <div class="ml-auto">
                            <button class="btn btn-primary btn-lg">Создать</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block bottom_js %}
{% render_bundle 'source_create_form' 'js' %}
{% endblock %}

source/templates/source_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

source/templates/source_list.html
{% extends 'cabinet_base.html' %}
{% load render_bundle from webpack_loader %}
{% block head_actions %}
    <a href="{% url 'source_create' %}" class="mb-2 mr-2 btn-icon btn btn-success"><i class="pe-7s-plus btn-icon-wrapper"> </i>Новый источник</a>
{% endblock %}
{% block main_area %}
    <div class="row">
        <div class="col-12">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="text-nowrap table-lg mb-0 table table-hover">
                            <thead>
                                <tr>
                                    <th class="text-center" style="width: 78px;">
                                        <div class="custom-checkbox custom-control">
                                            <input type="checkbox" name="head_checkbox" id="head_checkbox" class="custom-control-input">
                                            <label class="custom-control-label" for="head_checkbox">&nbsp;</label>
                                        </div>
                                    </th>
                                    <th>Название</th>
                                    <th>Описание</th>
                                    <th>Тип</th>
                                    <th>Действия</th>
                                </tr>
                            </thead>
                            <tbody>
                                <form action="{% url 'source_action' %}" id="actions_form" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" name="action" value="">
                                    {% for source in sources %}
                                        <tr>
                                            <td class="text-center" style="width: 78px;">
                                                <div class="custom-checkbox custom-control">
                                                    <input type="checkbox" name="id_list" id="list_select_{{ source.pk }}" value="{{ source.pk }}" class="custom-control-input list_checkbox">
                                                    <label class="custom-control-label" for="list_select_{{ source.pk }}">&nbsp;</label>
                                                </div>
                                            </td>
                                            <td>
                                                {{ source.name }}
                                            </td>
                                            <td>
                                                {{ source.description }}
                                            </td>
                                            <td>
                                                {{ source.get_import_type_display }}
                                            </td>
                                            <td>
                                                <div class="widget-content-right">
                                                    <button type="button" class="border-0 btn-transition btn btn-outline-success edit-item">
                                                        <i class="fa fa-info-circle"></i>
                                                    </button>
                                                    <button type="button" class="border-0 btn-transition btn btn-outline-danger action-item"
                                                            data-modal-title="Удалить источник?"
                                                            data-modal-message="После удаления, источник будет хранится в архиве вместе с товарами"
                                                            data-modal-action-button="Удалить"
                                                            data-modal-redirect="{% url 'source_delete' source.pk %}">
                                                        <i class="fa fa-trash-alt"></i>
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </form>
                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="d-block card-footer">
                    {% if page_obj.paginator.num_pages > 1 %}
                        <div class="mt-3 text-center">
                            {% include "_pagination.html" %}
                        </div>
                    {% endif %}
                    <div id="actions-bar" style="display: none">
                        <div class="mt-2">
                            <button class="mb-2 mr-2 btn btn-danger action-button" data-action-name="delete">В архив</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block bottom_js %}
    <div class="modal" id="actionModal">
      <div class="modal-dialog">
        <div class="modal-content">

          <!-- Modal Header -->
          <div class="modal-header">
            <h4 class="modal-title"></h4>
            <button type="button" class="close" data-dismiss="modal">&times;</button>
          </div>

          <!-- Modal body -->
          <div class="modal-body">

          </div>

          <!-- Modal footer -->
          <div class="modal-footer">
              <button type="button" class="btn btn-warning" data-dismiss="modal">Отмена</button>
              <a href="" class="btn btn-danger"></a>
          </div>

        </div>
      </div>
    </div>
    {% render_bundle 'list_tools' 'js' %}
{% endblock %}